export default [
  {
    id: "1",
    title: "Fast Reflex Save",
    duration: "00:07",
    source: "drill2_360.mov",
    category: "Reflex Training",
    videoUrl: "videos/snippets/reflex1.mp4",
    thumbnailUrl: "",
  },
  {
    id: "2",
    title: "Top Corner Save",
    duration: "00:05",
    source: "angle_top_view.mp4",
    category: "Positioning",
    videoUrl: "videos/snippets/positioning1.mp4",
    thumbnailUrl: "",
  },
  {
    id: "3",
    title: "Split Save",
    duration: "00:06",
    source: "save_high_3.mp4",
    category: "Reflex Training",
    videoUrl: "videos/snippets/reflex2.mp4",
    thumbnailUrl: "",
  },
  {
    id: "4",
    title: "Low Dive Save",
    duration: "00:06",
    source: "save_high_3.mp4",
    category: "Agility",
    videoUrl: "videos/snippets/agility1.mp4",
    thumbnailUrl: "",
  },
  {
    id: "5",
    title: "Quick Recovery",
    duration: "00:04",
    source: "deflection_test_5.mkv",
    category: "Recovery",
    videoUrl: "videos/snippets/recovery1.mp4",
    thumbnailUrl: "",
  },
  {
    id: "6",
    title: "Left Arm Block",
    duration: "00:05",
    source: "drill2_360.mov",
    category: "Blocking",
    videoUrl: "videos/snippets/blocking1.mp4",
    thumbnailUrl: "",
  },
  {
    id: "7",
    title: "Rebound Catch",
    duration: "00:06",
    source: "warmup_01.mp4",
    category: "Reflex Training",
    videoUrl: "videos/snippets/reflex3.mp4",
    thumbnailUrl: "",
  },
  {
    id: "8",
    title: "Angle Hold",
    duration: "00:08",
    source: "angle_top_view.mp4",
    category: "Positioning",
    videoUrl: "videos/snippets/positioning2.mp4",
    thumbnailUrl: "",
  },
  {
    id: "9",
    title: "Jump Save",
    duration: "00:07",
    source: "save_high_3.mp4",
    category: "Vertical Reach",
    videoUrl: "videos/snippets/jumpsave1.mp4",
    thumbnailUrl: "",
  },
  {
    id: "10",
    title: "Dive Left",
    duration: "00:06",
    source: "drill2_360.mov",
    category: "Agility",
    videoUrl: "videos/snippets/agility2.mp4",
    thumbnailUrl: "",
  },
  {
    id: "11",
    title: "Dive Right",
    duration: "00:06",
    source: "drill2_360.mov",
    category: "Agility",
    videoUrl: "videos/snippets/agility3.mp4",
    thumbnailUrl: "",
  },
  {
    id: "12",
    title: "Double Save",
    duration: "00:09",
    source: "save_high_3.mp4",
    category: "Reflex Training",
    videoUrl: "videos/snippets/reflex4.mp4",
    thumbnailUrl: "",
  },
  {
    id: "13",
    title: "Close-Range Block",
    duration: "00:05",
    source: "angle_top_view.mp4",
    category: "Blocking",
    videoUrl: "videos/snippets/blocking2.mp4",
    thumbnailUrl: "",
  },
  {
    id: "14",
    title: "Quick Reset",
    duration: "00:04",
    source: "warmup_01.mp4",
    category: "Recovery",
    videoUrl: "videos/snippets/recovery2.mp4",
    thumbnailUrl: "",
  },
  {
    id: "15",
    title: "Backpedal Control",
    duration: "00:07",
    source: "deflection_test_5.mkv",
    category: "Positioning",
    videoUrl: "videos/snippets/positioning3.mp4",
    thumbnailUrl: "",
  },
  {
    id: "16",
    title: "Stretch Block",
    duration: "00:06",
    source: "drill2_360.mov",
    category: "Flexibility",
    videoUrl: "videos/snippets/flex1.mp4",
    thumbnailUrl: "",
  },
  {
    id: "17",
    title: "One-Handed Save",
    duration: "00:05",
    source: "save_high_3.mp4",
    category: "Reflex Training",
    videoUrl: "videos/snippets/reflex5.mp4",
    thumbnailUrl: "",
  },
  {
    id: "18",
    title: "Fast Kick Save",
    duration: "00:05",
    source: "deflection_test_5.mkv",
    category: "Footwork",
    videoUrl: "videos/snippets/footwork1.mp4",
    thumbnailUrl: "",
  }
];
